### ISSUE TITLE
Bist du nicht mehr bei Twitter

### ISSUE THREAD

**Issue by apertureless** [roberttomsons/twitter_block_list#1]
See title

**Comment by roberttomsons** [comment]
Nope, habe mich abgemeldet. Bin nur noch per Tumblr oder Mail erreichbar. Muss mich hier auf meine Projekte (hackerb.it & Arbeit) konzentrieren und Twitter hat einfach zu viel Zeit gesaugt.

**Comment by roberttomsons** [comment]
Du kannst mich aber auch hier anschreiben, ist halt nur öffentlich. ;)

**Comment by apertureless** [comment]
gief tumblr 👀

**Comment by roberttomsons** [comment]
Ja, habe das jetzt auf meine Domain gelinkt. Keine Lust da gerade selber etwas zu machen.

**Comment by apertureless** [comment]
Check!
